using FishNet;
using FishNet.Connection;
using FishNet.Object;
using Unity.VisualScripting;
using UnityEngine;
using FishNet.Managing.Logging;
using UnityEngine.SceneManagement;

public class TrainLoader : MonoBehaviour
{
    // public SceneLoadingManager slm;

    [Server]
    private void OnTriggerEnter(Collider other)
    {
        if (!InstanceFinder.IsServer)
        {
            Debug.Log("ì„œë²„ êº¼ì§");
            return;
        }
        
        Debug.Log("íŠ¸ë¦¬ê±°ê°ì§€"); 
        NetworkObject nob = other.GetComponent<NetworkObject>();
        if (nob != null)
            LoadScene(nob);
    }

    private void LoadScene(NetworkObject nob)
    {
        if (!nob.Owner.IsActive)
        {
            return;
        }

        Debug.Log("ì”¬ë¡œë”© ìš”ì²­");

        // slm = SceneLoadingManager.Instance;

        // slm.CreateSessionFromTag(SceneType.Quiz, "MyStation", nob.Owner);
    }
    // public GameObject playerPrefab;
    // private SceneLoadingManager slm;
    // void Awake()
    // {
    //     NetworkObject nob = playerPrefab.GetComponent<NetworkObject>();

    //     slm = SceneLoadingManager.Instance;
    //     Debug.LogWarning("ğŸ”¥ MyStationLoader.Awake() í˜¸ì¶œë¨!");
    //     if (slm != null)
    //     {
    //         Debug.Log("dd");
    //         // OnCreateSessionButton(nob);

    //     }
    //     if (slm == null)
    //         Debug.Log("SessionManager ì¸ìŠ¤í„´ìŠ¤ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤!");
    // }
    // // public SessionManager sessionManager; // Inspectorì—ì„œ í• ë‹¹

    // // ë²„íŠ¼ì—ì„œ íƒœê·¸(string)ë¥¼ ë°›ì•„ì„œ ì„¸ì…˜ ìƒì„± ìš”ì²­
    // public void OnCreateSessionButton(NetworkObject nob)
    // {
    //     Debug.Log("ì”¬ ë¡œë”© ìš”ì²­");
    //     NetworkConnection conn = nob.Owner;
    //     // tag ì˜ˆì‹œ: "Lobby", "Game"
    //     // sessionManager.CreateSessionFromTagServerRpc(tag);
    //     // NetworkConnection conn = InstanceFinder.ClientManager.Connection;
    //     slm.CreateSessionFromTag(SceneType.Quiz, "MyStation", conn);
    // }
}
